pull_request_rules:
  - name: Put PR in draft if conflicts
    conditions:
      - label = conflicts
      - author = mergify[bot]
      - head ~= ^mergify/
    actions:
      edit:
        draft: true

  - name: Delete Mergify backport branch
    conditions:
      - base~=branch-
      - or:
          - merged
          - closed
    actions:
      delete_head_branch:

  - name: Automate backport pull request
    conditions:
      - or:
          - closed
          - merged
      - or:
          - base=master
          - base=next
      - body ~= (?m)^(close|fix|resolve)
      - label=promoted-to-master
      - label~=^backport/\d+\.\d+$
    actions:
      copy:
        title: "[Backport {{ label | replace('backport/', '') }}] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Refs #{{number}}
        branches:
          - branch-6.0
        assignees:
          - "{{ author }}"
