pull_request_rules:
  - name: Put PR in draft if conflicts
    conditions:
      - label=conflicts
      - author=mergify[bot]
      - head~=^mergify/
    actions:
      edit:
        draft: true

  - name: Delete Mergify backport branch
    conditions:
      - base~=branch-
      - or:
          - merged
          - closed
    actions:
      delete_head_branch: {}

  - name: Automate backport pull request
    conditions:
      - or:
          - closed
          - merged
      - or:
          - base=master
          - base=next
      - label=promoted-to-master
      - label~=^backport/\d+\.\d+$
      - body~=(?i)^(close|fix|resolve)
    actions:
      copy:
        title: |
            [Backport *^backport/\d+\.\d+$ ] {{ title }}
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Refs #{{ number }}
        branches:
          - label
        assignees:
          - "{{ author }}"
shared:
    backport/6.0: branch-6.0
    backport/6.1: branch-6.1
    backport/5.4: branch-5.4
