pull_request_rules:
  - name: Delete mergify backport branch
    conditions:
      - base~=next-
      - or:
        - merged
        - closed
    actions:
      delete_head_branch:
  - name:  Label original PR when backport has conflicts
    conditions:
      - conflict
    actions:
      label:
        add:
          - backport-conflict
      backport:
        branches:
          - next
  - name: Automate backport pull request 6.0
    conditions:
      - base=next # Ensure this rule only applies to PRs merged into the next branch
      - label=backport/6.0 # The PR must have this label to trigger the backport
      - label=promoted-to-master
    actions:
      backport:
        title: "[Backport 6.0] {{ title }}"
        body: |
          {{ body }}

          {% for c in commits %}
          (cherry picked from commit {{ c.sha }})
          {% endfor %}

          Parent PR: #{{number}}
        branches:
          - next-6.0
        assignees:
          - "{{ author }}"
        ignore_conflicts: false